<?xml version='1.0'?>
<robot xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

 <xacro:property name="M_PI" value="3.1415926535897931" />
 <xacro:property name="M_PI2" value="1.57079632679" />
 <!-- <xacro:property name="TRK_MESH" value="../trikey/meshes/low_res" /> -->

<!-- <xacro:include filename="$(find trikey)/xacro/omni_wheels_to_base.transmissions.xacro"/> -->
<!-- goddammit why does this not work?!!? -->
<!-- <xacro:include filename="omni_wheel.xacro"/> -->

<xacro:macro name="subwheel" params="wheel_name wheel_radius subwheel_number n_subwheels cos_2pi_n_over_N sin_2pi_n_over_N cos_pi_over_N sin_pi_over_N subwheel_mass subwheel_joint_type">

	<joint name="${wheel_name}_subwheel_${subwheel_number}_j" type="${subwheel_joint_type}">
		<origin xyz="${0.05*wheel_radius * cos_pi_over_N * cos_2pi_n_over_N} ${0.05*wheel_radius * cos_pi_over_N * sin_2pi_n_over_N} 0" rpy="0 0 ${2*M_PI*subwheel_number/n_subwheels}"/>
		<!-- <axis xyz="${-sin_2pi_n_over_N} ${cos_2pi_n_over_N} 0"/> -->
		<axis xyz="0 1 0"/>
		<parent link="${wheel_name}"/>
		<child link="${wheel_name}_subwheel_${subwheel_number}_l"/>
	</joint>

	<!-- <gazebo reference="${wheel_name}_subwheel_${subwheel_number}_j">
		<dynamics>
			<damping>10</damping>
			<friction>1</friction>
		</dynamics>
	</gazebo> -->

	<link name="${wheel_name}_subwheel_${subwheel_number}_l">
		<inertial>
			<mass value="${subwheel_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="${2*subwheel_mass*(wheel_radius*wheel_radius*sin_pi_over_N*sin_pi_over_N)/5}"
					 iyy="${2*subwheel_mass*(wheel_radius*wheel_radius*sin_pi_over_N*sin_pi_over_N)/5}"
					 izz="${2*subwheel_mass*(wheel_radius*wheel_radius*sin_pi_over_N*sin_pi_over_N)/5}"
					 ixy="0"
					 ixz="0"
					 iyz="0"/>
		</inertial>
		<!-- <visual name="${wheel_name}_subwheel_${subwheel_number}_vis">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="${wheel_name}_subwheel_${subwheel_number}_geom">
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</visual> -->
		<collision name="${wheel_name}_subwheel_${subwheel_number}_col">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="${wheel_name}_subwheel_${subwheel_number}_geom">
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<!-- <visual name="${wheel_name}_subwheel_${subwheel_number}_vis">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="${wheel_name}_subwheel_${subwheel_number}_geom">
				<sphere radius="${4.9 * wheel_radius * sin_pi_over_N}"/>
			</geometry>
		</visual>
		<collision name="${wheel_name}_subwheel_${subwheel_number}_col">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="${wheel_name}_subwheel_${subwheel_number}_geom">
				<sphere radius="${4.9 * wheel_radius * sin_pi_over_N}"/>
			</geometry>
		</collision> -->
	</link>

</xacro:macro>

<xacro:macro name="omni_wheel_18subs" params="wheel_name wheel_radius wheel_mass wheel_visual ixx iyy izz ixy ixz iyz subwheel_mass subwheel_joint_type color">
	<link name="${wheel_name}">
		<inertial>
			<mass value="${wheel_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="${ixx}" iyy="${iyy}" izz="${izz}" ixy="${ixy}" ixz="${ixz}" iyz="${iyz}"/>
		</inertial>
		<visual name="${wheel_name}_vis">
			<origin xyz="0 0 0.05" rpy="0 0 0"/>
		    <geometry name="${wheel_name}_geom">
		    	<!-- <cylinder length="0.025" radius="${wheel_radius}"/> -->
		      	<mesh filename="${wheel_visual}"/>
		    </geometry>

            <material name="grey">
                <color rgba="0.627 0.627 0.627 1"/>
            </material>
		</visual>
		<collision name="${wheel_name}_col">
			 <origin xyz="0 0.0 0" rpy="0 0 0"/>
		     <geometry name="${wheel_name}_geom">
		     	<cylinder length="0.025" radius="${wheel_radius}"/>
		     </geometry>
		</collision>
	</link>
	<gazebo reference="${wheel_name}">
		<material>Gazebo/${color}</material>
	</gazebo>
	<!-- <gazebo reference="${wheel_name}">
		<mu1>0</mu1>
		<mu2>1</mu2>
		<fdir1>0 0 1</fdir1>
	</gazebo> -->

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="0" n_subwheels="18" cos_2pi_n_over_N="1" sin_2pi_n_over_N="0" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="1" n_subwheels="18" cos_2pi_n_over_N="0.939692620785908" sin_2pi_n_over_N="0.342020143325669" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="2" n_subwheels="18" cos_2pi_n_over_N="0.766044443118978" sin_2pi_n_over_N="0.642787609686539" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="3" n_subwheels="18" cos_2pi_n_over_N="0.5" sin_2pi_n_over_N="0.866025403784439" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="4" n_subwheels="18" cos_2pi_n_over_N="0.17364817766693" sin_2pi_n_over_N="0.984807753012208" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="5" n_subwheels="18" cos_2pi_n_over_N="-0.17364817766693" sin_2pi_n_over_N="0.984807753012208" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="6" n_subwheels="18" cos_2pi_n_over_N="-0.5" sin_2pi_n_over_N="0.866025403784439" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="7" n_subwheels="18" cos_2pi_n_over_N="-0.766044443118978" sin_2pi_n_over_N="0.64278760968654" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="8" n_subwheels="18" cos_2pi_n_over_N="-0.939692620785908" sin_2pi_n_over_N="0.342020143325669" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="9" n_subwheels="18" cos_2pi_n_over_N="-1" sin_2pi_n_over_N="0.0" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="10" n_subwheels="18" cos_2pi_n_over_N="-0.939692620785908" sin_2pi_n_over_N="-0.342020143325669" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="11" n_subwheels="18" cos_2pi_n_over_N="-0.766044443118978" sin_2pi_n_over_N="-0.642787609686539" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="12" n_subwheels="18" cos_2pi_n_over_N="-0.5" sin_2pi_n_over_N="-0.866025403784438" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="13" n_subwheels="18" cos_2pi_n_over_N="-0.17364817766693" sin_2pi_n_over_N="-0.984807753012208" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="14" n_subwheels="18" cos_2pi_n_over_N="0.17364817766693" sin_2pi_n_over_N="-0.984807753012208" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="15" n_subwheels="18" cos_2pi_n_over_N="0.5" sin_2pi_n_over_N="-0.866025403784439" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="16" n_subwheels="18" cos_2pi_n_over_N="0.766044443118978" sin_2pi_n_over_N="-0.64278760968654" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

	<xacro:subwheel wheel_name="${wheel_name}" wheel_radius="${wheel_radius}" subwheel_number="17" n_subwheels="18" cos_2pi_n_over_N="0.939692620785908" sin_2pi_n_over_N="-0.342020143325669" cos_pi_over_N="0.984807753012208" sin_pi_over_N="0.17364817766693" subwheel_mass="${subwheel_mass}" subwheel_joint_type="${subwheel_joint_type}"/>

</xacro:macro>

</robot>